In [ ]:
import pandas as pd

In [ ]:
data = pd.read_json('News_Category_Dataset_v3.json',lines=True)

### Data Exploration

In [ ]:
data.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [ ]:
data.shape

(209527, 6)

In [ ]:
data.isnull().sum()

link                 0
headline             0
category             0
short_description    0
authors              0
date                 0
dtype: int64

In [ ]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='object')

In [ ]:
data = data['short_description'].head(20000)

In [ ]:
data

0        Health experts said it is too early to predict...
1        He was subdued by passengers and crew when he ...
2        "Until you have a dog you don't understand wha...
3        "Accidentally put grown-up toothpaste on my to...
4        Amy Cooper accused investment firm Franklin Te...
                               ...
19995    He and his wife Grace would be granted full im...
19996    Transition is the name of the game in the Midd...
19997    The breakdown of coalition talks has plunged G...
19998    In a major, thorough and truly important piece...
19999    In recent weeks, Saudi Arabia has become more ...
Name: short_description, Length: 20000, dtype: object

In [ ]:
data[0]

'Health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the U.S. ordered for the fall.'

In [ ]:
data.isnull().sum()

np.int64(0)

In [ ]:
data.duplicated().sum()

np.int64(66)

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.shape

(19934,)

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.reset_index(drop=True,inplace=True)

In [ ]:
data

0        Health experts said it is too early to predict...
1        He was subdued by passengers and crew when he ...
2        "Until you have a dog you don't understand wha...
3        "Accidentally put grown-up toothpaste on my to...
4        Amy Cooper accused investment firm Franklin Te...
                               ...
19929    He and his wife Grace would be granted full im...
19930    Transition is the name of the game in the Midd...
19931    The breakdown of coalition talks has plunged G...
19932    In a major, thorough and truly important piece...
19933    In recent weeks, Saudi Arabia has become more ...
Name: short_description, Length: 19934, dtype: object

### Preprocessing

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, Input, Dense, LSTM
from keras.utils import pad_sequences

In [ ]:
import keras

In [ ]:
print(keras.__version__)

3.13.2

In [ ]:
tokenizer = Tokenizer(oov_token='<OOV>')

In [ ]:
tokenizer.fit_on_texts(data)

In [ ]:
tokenizer.word_counts

OrderedDict([('health', 203),
             ('experts', 106),
             ('said', 2294),
             ('it', 1482),
             ('is', 2832),
             ('too', 204),
             ('early', 71),
             ('to', 8110),
             ('predict', 6),
             ('whether', 107),
             ('demand', 27),
             ('would', 470),
             ('match', 16),
             ('up', 644),
             ('with', 1807),
             ('the', 21016),
             ('171', 1),
             ('million', 172),
             ('doses', 8),
             ('of', 6850),
             ('new', 1018),
             ('boosters', 1),
             ('u', 637),
             ('s', 622),
             ('ordered', 32),
             ('for', 3262),
             ('fall', 46),
             ('he', 1391),
             ('was', 2038),
             ('subdued', 1),
             ('by', 1042),
             ('passengers', 19),
             ('and', 5591),
             ('crew', 15),
             ('when', 492),
             ('fled', 18),
             ('back', 307),
             ('aircraft', 12),
             ('after', 976),
             ('confrontation', 8),
             ('according', 153),
             ("attorney's", 2),
             ('office', 144),
             ('in', 5456),
             ('los', 43),
             ('angeles', 40),
             ('until', 76),
             ('you', 956),
             ('have', 1309),
             ('a', 8060),
             ('dog', 31),
             ("don't", 176),
             ('understand', 27),
             ('what', 543),
             ('could', 408),
             ('be', 1232),
             ('eaten', 3),
             ('accidentally', 8),
             ('put', 137),
             ('grown', 10),
             ('toothpaste', 2),
             ('on', 2741),
             ('my', 359),
             ('toddler’s', 1),
             ('toothbrush', 1),
             ('screamed', 2),
             ('like', 455),
             ('i', 928),
             ('cleaning', 9),
             ('his', 1754),
             ('teeth', 11),
             ('carolina', 39),
             ('reaper', 1),
             ('dipped', 2),
             ('tabasco', 1),
             ('sauce', 3),
             ('amy', 19),
             ('cooper', 14),
             ('accused', 243),
             ('investment', 7),
             ('firm', 27),
             ('franklin', 6),
             ('templeton', 1),
             ('unfairly', 3),
             ('firing', 15),
             ('her', 1026),
             ('branding', 2),
             ('racist', 54),
             ('video', 173),
             ('central', 33),
             ('park', 51),
             ('encounter', 16),
             ('went', 111),
             ('viral', 52),
             ('63', 9),
             ('year', 699),
             ('old', 351),
             ('woman', 177),
             ('seen', 66),
             ('working', 95),
             ('at', 1458),
             ('south', 95),
             ('store', 27),
             ('thursday', 62),
             ('she', 638),
             ('found', 172),
             ('dead', 92),
             ('monday', 121),
             ('family', 179),
             ('reported', 106),
             ('missing', 46),
             ('authorities', 97),
             ("who's", 35),
             ('that', 2207),
             ('behind', 81),
             ('an', 1287),
             ('anchor', 49),
             ('york’s', 4),
             ('pix11', 1),
             ('asked', 127),
             ('journalist', 39),
             ('michelle', 19),
             ('ross', 8),
             ('as', 1350),
             ('finished', 11),
             ('interview', 84),
             ('more', 770),
             ('than', 506),
             ('half', 61),
             ('people', 848),
             ('remained', 16),
             ('without', 137),
             ('water', 66),
             ('service', 79),
             ('three', 210),
             ('days', 178),
             ('storm', 42),
             ('lashed', 6),
             ('territory', 14),
             ('mija', 1),
             ('director', 148),
             ('isabel', 1),
             ('castro', 6),
             ('combined', 8),
             ('music', 79),
             ('documentaries', 2),
             ('style', 30),
             ('euphoria', 3),
             ('clueless', 6),
             ('tell', 99),
             ('nuanced', 4),
             ('immigration', 69),
             ('story', 112),
             ('white', 401),
             ('house', 509),
             ('officials', 223),
             ('say', 426),
             ('crux', 1),
             ("president's", 188),
             ('visit', 46),
             ('n', 39),
             ('this', 1174),
             ('will', 914),
             ('full', 73),
             ('throated', 1),
             ('condemnation', 5),
             ('russia', 113),
             ('its', 394),
             ('brutal', 13),
             ('war', 128),
             ('fifa', 1),
             ('has', 1325),
             ('come', 132),
             ('under', 141),
             ('pressure', 39),
             ('from', 1241),
             ('several', 101),
             ('european', 28),
             ('soccer', 23),
             ('federations', 1),
             ('who', 935),
             ('want', 222),
             ('support', 142),
             ('human', 58),
             ('rights', 169),
             ('campaign', 225),
             ('against', 392),
             ('discrimination', 34),
             ('world', 240),
             ('cup', 11),
             ('incident', 59),
             ('underscores', 7),
             ('growing', 43),
             ('wave', 29),
             ('protests', 55),
             ('funeral', 14),
             ('shinzo', 2),
             ('abe', 2),
             ('one', 875),
             ('most', 274),
             ('divisive', 8),
             ('leaders', 99),
             ('postwar', 1),
             ('japanese', 16),
             ('politics', 58),
             ('hurricane', 35),
             ('fiona', 1),
             ('turks', 4),
             ('caicos', 2),
             ('islands', 8),
             ('forecast', 5),
             ('squeeze', 1),
             ('past', 94),
             ('bermuda', 1),
             ('later', 77),
             ('week', 313),
             ("man's", 12),
             ('claims', 106),
             ('scammed', 2),
             ('platform', 32),
             ('caused', 36),
             ('popular', 48),
             ('streamers', 1),
             ('consider', 22),
             ('twitch', 1),
             ('boycott', 7),
             ('conservative', 81),
             ('activist', 60),
             ('virginia', 52),
             ('thomas', 33),
             ('wife', 76),
             ('supreme', 88),
             ('court', 205),
             ('justice', 142),
             ('clarence', 6),
             ('agreed', 25),
             ('participate', 5),
             ('voluntary', 2),
             ('panel', 20),
             ('investigating', 46),
             ('jan', 63),
             ('6', 87),
             ('insurrection', 26),
             ("polyakov's", 1),
             ('record', 70),
             ('breaking', 35),
             ('trip', 44),
             ('outer', 3),
             ('space', 39),
             ('saw', 45),
             ('him', 344),
             ('orbit', 7),
             ('earth', 24),
             ('7', 47),
             ('075', 1),
             ('times', 147),
             ('travel', 41),
             ('nearly', 105),
             ('187', 1),
             ('miles', 32),
             ('starring', 22),
             ('keegan', 1),
             ('michael', 123),
             ('key', 47),
             ('judy', 3),
             ('greer', 3),
             ('johnny', 5),
             ('knoxville', 2),
             ('hulu', 7),
             ('show', 441),
             ('follows', 40),
             ('revival', 10),
             ('fictional', 5),
             ('2000s', 3),
             ('sitcom', 9),
             ('maury', 1),
             ('wills', 1),
             ('helped', 51),
             ('dodgers', 5),
             ('win', 75),
             ('series', 117),
             ('titles', 6),
             ('base', 10),
             ('stealing', 5),
             ('prowess', 2),
             ('died', 133),
             ('concerted', 1),
             ('quickening', 1),
             ('kremlin', 16),
             ('backed', 30),
             ('efforts', 58),
             ('swallow', 2),
             ('four', 116),
             ('regions', 3),
             ('set', 134),
             ('stage', 46),
             ('moscow', 19),
             ('escalate', 2),
             ('government', 205),
             ('imposed', 16),
             ('curfew', 2),
             ('intensifying', 4),
             ('kept', 30),
             ('dropping', 13),
             ('copious', 2),
             ('rain', 19),
             ('over', 522),
             ('dominican', 4),
             ('republic', 11),
             ('puerto', 11),
             ('rico', 7),
             ('18', 65),
             ('months', 110),
             ('hollywood', 63),
             ('effectively', 8),
             ('boycotted', 1),
             ('globes', 17),
             ('reports', 64),
             ('hfpa’s', 1),
             ('87', 5),
             ('members', 104),
             ('non', 30),
             ('american', 223),
             ('journalists', 23),
             ('included', 26),
             ('no', 472),
             ('black', 276),
             ('president', 1178),
             ('issues', 68),
             ('vow', 3),
             ('tensions', 15),
             ('china', 39),
             ('rise', 37),
             ('knocked', 14),
             ('out', 678),
             ('power', 124),
             ('grid', 6),
             ('unleashed', 2),
             ('floods', 7),
             ('landslides', 2),
             ('where', 176),
             ('governor', 93),
             ('damage', 27),
             ('“catastrophic', 1),
             ('”', 1111),
             ('single', 48),
             ('engine', 5),
             ('plane', 30),
             ('participating', 5),
             ('national', 198),
             ('championship', 4),
             ('air', 69),
             ('races', 13),
             ('sunday', 160),
             ('crashed', 17),
             ('into', 449),
             ('field', 30),
             ('killing', 68),
             ('pilot', 19),
             ('annual', 32),
             ('celebration', 9),
             ('took', 152),
             ('different', 60),
             ('feel', 77),
             ("russia's", 28),
             ('invasion', 21),
             ('dragged', 5),
             ('day', 327),
             ('206', 1),
             ('mark', 59),
             ('frerichs', 1),
             ('navy', 17),
             ('veteran', 43),
             ('civilian', 9),
             ('contractor', 4),
             ('kidnapped', 5),
             ('afghanistan', 13),
             ('january', 27),
             ('2020', 94),
             ('las', 17),
             ('vegas', 18),
             ('never', 162),
             ('had', 522),
             ('professional', 15),
             ('sports', 40),
             ('champion', 19),
             ('—', 269),
             ('joe', 129),
             ('biden', 169),
             ('first', 526),
             ('lady', 62),
             ('jill', 8),
             ('were', 633),
             ('among', 89),
             ('thousands', 95),
             ('mourners', 2),
             ('locals', 2),
             ('tourists', 8),
             ('royals', 1),
             ('pay', 79),
             ('their', 748),
             ('respects', 4),
             ('avatar', 2),
             ('aspects', 4),
             ('2009', 5),
             ('movie', 107),
             ('are', 1378),
             ('still', 213),
             ('competitive', 4),
             ('everything', 60),
             ('that’s', 58),
             ('there', 307),
             ('these', 244),
             ('alain', 1),
             ('robert', 72),
             ('known', 87),
             ('french', 36),
             ('spider', 8),
             ('man', 254),
             ('climbed', 4),
             ('burj', 1),
             ('khalifa', 1),
             ('empire', 8),
             ('state', 453),
             ('building', 45),
             ('london', 25),
             ('queen', 40),
             ('elizabeth', 34),
             ('ii', 17),
             ('says', 496),
             ('heart', 49),
             ('royal', 30),
             ('adding', 13),
             ('queen’s', 1),
             ('death', 158),
             ('left', 116),
             ('“giant', 2),
             ('hole', 7),
             ('despite', 70),
             ('entering', 16),
             ('false', 38),
             ('information', 83),
             ('work', 164),
             ("wasn't", 50),
             ('redone', 1),
             ('fully', 23),
             ('some', 465),
             ('cases', 72),
             ('census', 18),
             ('takers', 1),
             ('received', 73),
             ('bonuses', 7),
             ('inspector', 7),
             ('general', 115),
             ('world’s', 7),
             ('public', 182),
             ('database', 4),
             ('fossil', 11),
             ('fuel', 24),
             ('production', 7),
             ('reserves', 2),
             ('emissions', 6),
             ('launches', 4),
             ('19', 226),
             ('reportedly', 184),
             ('thames', 1),
             ('failed', 43),
             ('bid', 19),
             ('escape', 16),
             ('police', 305),
             ('“in', 11),
             ('10', 114),
             ('years', 336),
             ('referring', 5),
             ('september', 19),
             ('2022', 19),
             ('benchmark', 2),
             ('watch', 65),
             ('saturday', 91),
             ('barreled', 2),
             ('towards', 12),
             ('organization', 53),
             ('raising', 18),
             ('alarm', 8),
             ('about', 1091),
             ('“second', 1),
             ('disaster”', 1),
             ('wake', 32),
             ('deadly', 32),
             ('pakistan', 10),
             ('summer', 32),
             ('doctors', 19),
             ('medical', 41),
             ('workers', 79),
             ('ground', 37),
             ('race', 80),
             ('battle', 39),
             ('outbreaks', 9),
             ('waterborne', 1),
             ('other', 303),
             ('diseases', 3),
             ('studies', 10),
             ('repeatedly', 30),
             ('shown', 9),
             ('ending', 23),
             ('administration', 159),
             ('supplies', 7),
             ('doesn’t', 62),
             ('but', 990),
             ('now', 400),
             ('table', 18),
             ('mississippi', 18),
             ('“never', 3),
             ('history', 153),
             ('duesseldorf', 1),
             ('customs', 9),
             ('trail', 8),
             ('slime', 3),
             ('led', 86),
             ('us', 202),
             ('smuggled', 1),
             ('goods', 11),
             ('spokesman', 19),
             ('walk', 26),
             ('told', 336),
             ('media', 202),
             ('original', 29),
             ('1982', 3),
             ('film', 131),
             ('joins', 24),
             ('writer', 36),
             ('2017', 83),
             ('sequel', 9),
             ('newest', 7),
             ('installment', 9),
             ('sci', 8),
             ('fi', 9),
             ('franchise', 10),
             ('republican', 253),
             ('outrage', 17),
             ('shoddy', 3),
             ('withdrawal', 6),
             ('hasn’t', 13),
             ('spurred', 6),
             ('resettling', 1),
             ('refugees', 24),
             ('sarah', 18),
             ('collins', 13),
             ('rudolph', 7),
             ('lost', 66),
             ('eye', 28),
             ('pieces', 7),
             ('glass', 7),
             ('inside', 53),
             ('body', 45),
             ('ku', 4),
             ('klux', 4),
             ('klan', 4),
             ('bombing', 9),
             ('killed', 179),
             ('sister', 22),
             ('girls', 53),
             ('alabama', 53),
             ('church', 46),
             ('59', 7),
             ('ago', 92),
             ('boil', 2),
             ('advisory', 3),
             ('been', 743),
             ('lifted', 8),
             ("mississippi's", 4),
             ('capital', 39),
             ('stop', 100),
             ('handing', 4),
             ('free', 79),
             ('bottled', 3),
             ('“the', 138),
             ('phantom', 2),
             ('opera”', 1),
             ('broadway’s', 1),
             ('longest', 13),
             ('running', 71),
             ('scheduled', 26),
             ('close', 48),
             ('february', 21),
             ('2023', 2),
             ('victim', 44),
             ('post', 119),
             ('pandemic', 167),
             ('softening', 2),
             ('theater', 10),
             ('attendance', 6),
             ('york', 198),
             ('former', 662),
             ('chief', 98),
             ('staff', 63),
             ('turned', 60),
             ('records', 29),
             ('part', 135),
             ('federal', 194),
             ('investigation', 138),
             ('2021', 23),
             ('assault', 101),
             ('capitol', 79),
             ('colombian', 2),
             ("author's", 5),
             ('book', 62),
             ('lightlark', 1),
             ('rejected', 21),
             ('numerous', 7),
             ('directly', 15),
             ('readers', 13),
             ('mykel', 1),
             ('gordon', 10),
             ('rushed', 6),
             ("woman's", 13),
             ('aid', 35),
             ('held', 70),
             ('down', 222),
             ('assailant', 1),
             ('arrived', 13),
             ('remarkably', 3),
             ('time', 431),
             ('may', 261),
             ('saved', 13),
             ('life', 191),
             ('oscar', 44),
             ('winner', 37),
             ('worked', 42),
             ('five', 110),
             ('hours', 72),
             ('role', 83),
             ('action', 98),
             ('reality', 50),
             ('star', 368),
             ('james', 67),
             ('corden', 14),
             ("she's", 82),
             ('branching', 1),
             ('because', 212),
             ('clearly', 19),
             ("it's", 451),
             ('not', 1015),
             ('whatever', 10),
             ('i’m', 92),
             ('doing', 63),
             ('podcasters', 2),
             ('hoping', 22),
             ('find', 77),
             ('shot', 127),
             ('rap', 6),
             ('icon', 35),
             ('26', 17),
             ('grammy', 18),
             ('winning', 53),
             ('rapper', 80),
             ('surprised', 18),
             ('struck', 38),
             ('children', 146),
             ('alexander', 14),
             ('macomb', 1),
             ('school', 225),
             ('morris', 8),
             ('heights', 7),
             ('make', 268),
             ('announcement', 35),
             ('richardson', 5),
             ('ambassador', 26),
             ('united', 106),
             ('nations', 45),
             ('frequent', 2),
             ('emissary', 1),
             ('hostage', 7),
             ('negotiations', 19),
             ('meetings', 5),
             ('russian', 114),
             ('television', 15),
             ('awards', 47),
             ('ceremony', 56),
             ('roughly', 14),
             ('1', 143),
             ('5', 81),
             ('viewers', 31),
             ('compared', 22),
             ('program', 62),
             ('press', 99),
             ('secretary', 168),

In [ ]:
len(tokenizer.word_counts)

26342

In [ ]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'for': 8,
 'is': 9,
 'on': 10,
 'said': 11,
 'that': 12,
 'was': 13,
 'with': 14,
 'his': 15,
 'it': 16,
 'at': 17,
 'he': 18,
 'are': 19,
 'as': 20,
 'has': 21,
 'have': 22,
 'an': 23,
 'from': 24,
 'be': 25,
 'president': 26,
 'this': 27,
 'trump': 28,
 '”': 29,
 'about': 30,
 'by': 31,
 'her': 32,
 'new': 33,
 'not': 34,
 'but': 35,
 'after': 36,
 'you': 37,
 'who': 38,
 'i': 39,
 'will': 40,
 'one': 41,
 'people': 42,
 'more': 43,
 'their': 44,
 'been': 45,
 'year': 46,
 'out': 47,
 'former': 48,
 'they': 49,
 'up': 50,
 'she': 51,
 'u': 52,
 'were': 53,
 's': 54,
 'all': 55,
 'we': 56,
 'just': 57,
 'what': 58,
 'first': 59,
 'over': 60,
 'had': 61,
 'house': 62,
 'than': 63,
 'says': 64,
 'when': 65,
 'two': 66,
 'no': 67,
 'would': 68,
 'or': 69,
 'some': 70,
 'like': 71,
 'state': 72,
 "it's": 73,
 'into': 74,
 'show': 75,
 'if': 76,
 'also': 77,
 'time': 78,
 'say': 79,
 'last': 80,
 'your': 81,
 'could': 82,
 'can': 83,
 'host': 84,
 'white': 85,
 'now': 86,
 'how': 87,
 'its': 88,
 'against': 89,
 'so': 90,
 'during': 91,
 'star': 92,
 'my': 93,
 'old': 94,
 'do': 95,
 'him': 96,
 'news': 97,
 'years': 98,
 'told': 99,
 "trump's": 100,
 'our': 101,
 'day': 102,
 'donald': 103,
 'women': 104,
 'get': 105,
 'week': 106,
 'back': 107,
 'there': 108,
 'police': 109,
 'other': 110,
 'before': 111,
 'which': 112,
 'made': 113,
 'even': 114,
 'them': 115,
 'black': 116,
 'most': 117,
 'actor': 118,
 '—': 119,
 'make': 120,
 'being': 121,
 'called': 122,
 'may': 123,
 'country': 124,
 'man': 125,
 'republican': 126,
 'me': 127,
 'while': 128,
 'know': 129,
 'late': 130,
 'only': 131,
 'these': 132,
 'accused': 133,
 'off': 134,
 'world': 135,
 'many': 136,
 'sexual': 137,
 'since': 138,
 '19': 139,
 'it’s': 140,
 'right': 141,
 'campaign': 142,
 'school': 143,
 'officials': 144,
 'american': 145,
 'want': 146,
 'down': 147,
 'coronavirus': 148,
 '000': 149,
 'still': 150,
 'because': 151,
 'covid': 152,
 'three': 153,
 'should': 154,
 'take': 155,
 'democratic': 156,
 'court': 157,
 'government': 158,
 'election': 159,
 'going': 160,
 'wrote': 161,
 'too': 162,
 'health': 163,
 'us': 164,
 'media': 165,
 'way': 166,
 'bill': 167,
 'national': 168,
 'york': 169,
 'long': 170,
 'did': 171,
 'much': 172,
 'federal': 173,
 'gop': 174,
 'law': 175,
 'life': 176,
 'got': 177,
 'twitter': 178,
 "president's": 179,
 'states': 180,
 'home': 181,
 'reportedly': 182,
 '“i': 183,
 'public': 184,
 'fox': 185,
 'family': 186,
 'killed': 187,
 'days': 188,
 'senator': 189,
 'good': 190,
 'woman': 191,
 "don't": 192,
 'where': 193,
 'think': 194,
 'really': 195,
 'video': 196,
 'senate': 197,
 'million': 198,
 'found': 199,
 'go': 200,
 'help': 201,
 'attorney': 202,
 'rights': 203,
 'biden': 204,
 'secretary': 205,
 'any': 206,
 'least': 207,
 'pandemic': 208,
 'own': 209,
 'singer': 210,
 'city': 211,
 'attack': 212,
 'work': 213,
 'republicans': 214,
 'never': 215,
 'democrats': 216,
 'why': 217,
 'sunday': 218,
 'need': 219,
 'administration': 220,
 'face': 221,
 'gun': 222,
 'death': 223,
 'actress': 224,
 'social': 225,
 'month': 226,
 'those': 227,
 "he's": 228,
 'very': 229,
 'rep': 230,
 'according': 231,
 'history': 232,
 'took': 233,
 'anti': 234,
 'end': 235,
 'night': 236,
 'director': 237,
 'look': 238,
 'political': 239,
 'times': 240,
 'children': 241,
 'best': 242,
 'big': 243,
 'group': 244,
 'around': 245,
 'don’t': 246,
 'office': 247,
 'change': 248,
 '1': 249,
 'support': 250,
 'justice': 251,
 'next': 252,
 'men': 253,
 'under': 254,
 '“the': 255,
 'investigation': 256,
 'decision': 257,
 'put': 258,
 'without': 259,
 'high': 260,
 'love': 261,
 'part': 262,
 'congress': 263,
 'company': 264,
 'set': 265,
 'through': 266,
 'died': 267,
 'security': 268,
 'see': 269,
 'between': 270,
 'used': 271,
 'party': 272,
 'come': 273,
 'department': 274,
 'including': 275,
 'another': 276,
 'here': 277,
 'young': 278,
 'film': 279,
 'vote': 280,
 'comes': 281,
 'north': 282,
 'joe': 283,
 'well': 284,
 'war': 285,
 'california': 286,
 'ever': 287,
 'case': 288,
 'asked': 289,
 'shot': 290,
 'care': 291,
 'americans': 292,
 'sen': 293,
 'hit': 294,
 'second': 295,
 'special': 296,
 'same': 297,
 'deal': 298,
 'official': 299,
 'power': 300,
 'latest': 301,
 'again': 302,
 'little': 303,
 'michael': 304,
 'move': 305,
 'lot': 306,
 'monday': 307,
 'team': 308,
 'leader': 309,
 'top': 310,
 'post': 311,
 'every': 312,
 'both': 313,
 'use': 314,
 'far': 315,
 'away': 316,
 'shooting': 317,
 'came': 318,
 'report': 319,
 'series': 320,
 'washington': 321,
 'four': 322,
 'left': 323,
 'getting': 324,
 'person': 325,
 "didn't": 326,
 'lawmakers': 327,
 'general': 328,
 "here's": 329,
 '10': 330,
 'russian': 331,
 'shows': 332,
 'florida': 333,
 'russia': 334,
 'things': 335,
 'story': 336,
 'fire': 337,
 'went': 338,
 'allegations': 339,
 'months': 340,
 'five': 341,
 'co': 342,
 'wants': 343,
 'believe': 344,
 'presidential': 345,
 'call': 346,
 'whether': 347,
 'movie': 348,
 'military': 349,
 'thing': 350,
 'tax': 351,
 'experts': 352,
 'reported': 353,
 'claims': 354,
 'united': 355,
 'response': 356,
 'money': 357,
 'john': 358,
 'nearly': 359,
 'making': 360,
 'trying': 361,
 'members': 362,
 'violence': 363,
 'america': 364,
 'already': 365,
 'across': 366,
 'texas': 367,
 'gov': 368,
 'does': 369,
 'several': 370,
 'assault': 371,
 "doesn't": 372,
 'tv': 373,
 'coming': 374,
 'then': 375,
 'stop': 376,
 'trump’s': 377,
 'run': 378,
 'tell': 379,
 'leaders': 380,
 'press': 381,
 'something': 382,
 'harassment': 383,
 'tweeted': 384,
 'once': 385,
 'chief': 386,
 'action': 387,
 'judge': 388,
 'sex': 389,
 'recent': 390,
 'policy': 391,
 'authorities': 392,
 'announced': 393,
 'climate': 394,
 'kids': 395,
 'comedian': 396,
 'talk': 397,
 'season': 398,
 'daughter': 399,
 'candidate': 400,
 'control': 401,
 'working': 402,
 'south': 403,
 'thousands': 404,
 'place': 405,
 'live': 406,
 'weeks': 407,
 'past': 408,
 '2020': 409,
 'students': 410,
 'legal': 411,
 'governor': 412,
 "they're": 413,
 'tuesday': 414,
 'others': 415,
 'amid': 416,
 'real': 417,
 'dead': 418,
 'ago': 419,
 'i’m': 420,
 'major': 421,
 'child': 422,
 'fbi': 423,
 'keep': 424,
 'saturday': 425,
 'food': 426,
 'd': 427,
 'parents': 428,
 'calling': 429,
 'comments': 430,
 'give': 431,
 'among': 432,
 '2016': 433,
 'open': 434,
 'supreme': 435,
 'event': 436,
 '2': 437,
 'allegedly': 438,
 'cnn': 439,
 'won': 440,
 'few': 441,
 '6': 442,
 'known': 443,
 'claimed': 444,
 'head': 445,
 'expected': 446,
 'friday': 447,
 'vice': 448,
 'son': 449,
 'led': 450,
 'plan': 451,
 'following': 452,
 'abuse': 453,
 'charges': 454,
 'wanted': 455,
 "there's": 456,
 'interview': 457,
 'name': 458,
 'saying': 459,
 'information': 460,
 '2017': 461,
 'role': 462,
 'taking': 463,
 'lgbtq': 464,
 "she's": 465,
 "won't": 466,
 'instagram': 467,
 'democrat': 468,
 'yet': 469,
 'bad': 470,
 'behind': 471,
 'conservative': 472,
 '5': 473,
 "can't": 474,
 'enough': 475,
 'race': 476,
 'rapper': 477,
 'game': 478,
 'great': 479,
 'committee': 480,
 'number': 481,
 'voters': 482,
 'actually': 483,
 'service': 484,
 'music': 485,
 'pay': 486,
 'workers': 487,
 'free': 488,
 'capitol': 489,
 "that's": 490,
 'job': 491,
 'community': 492,
 'king': 493,
 'six': 494,
 'earlier': 495,
 'lives': 496,
 'meeting': 497,
 'wednesday': 498,
 'border': 499,
 'later': 500,
 'feel': 501,
 'find': 502,
 'misconduct': 503,
 'fired': 504,
 'future': 505,
 'gave': 506,
 'until': 507,
 'wife': 508,
 'using': 509,
 'groups': 510,
 'might': 511,
 'movement': 512,
 'win': 513,
 'plans': 514,
 'defense': 515,
 '3': 516,
 'almost': 517,
 'himself': 518,
 '20': 519,
 'words': 520,
 'become': 521,
 'though': 522,
 'question': 523,
 'thought': 524,
 'fight': 525,
 'hundreds': 526,
 '“we': 527,
 'moment': 528,
 'full': 529,
 'received': 530,
 'ukraine': 531,
 'abortion': 532,
 'released': 533,
 'fans': 534,
 '2018': 535,
 'robert': 536,
 'cases': 537,
 'hours': 538,
 'likely': 539,
 'lawyer': 540,
 'mass': 541,
 'prison': 542,
 'better': 543,
 'early': 544,
 'running': 545,
 'red': 546,
 'agency': 547,
 'laws': 548,
 "you're": 549,
 'act': 550,
 'facebook': 551,
 'must': 552,
 'looking': 553,
 'didn’t': 554,
 'crisis': 555,
 'everyone': 556,
 'today': 557,
 'record': 558,
 'despite': 559,
 'held': 560,
 'mayor': 561,
 'having': 562,
 'decades': 563,
 'prime': 564,
 'taken': 565,
 'always': 566,
 'victims': 567,
 'immigration': 568,
 'air': 569,
 'attacks': 570,
 'step': 571,
 'previously': 572,
 'hard': 573,
 'local': 574,
 'daily': 575,
 'am': 576,
 'nothing': 577,
 'issues': 578,
 'killing': 579,
 'order': 580,
 'minister': 581,
 'force': 582,
 'percent': 583,
 'james': 584,
 'message': 585,
 'david': 586,
 'photo': 587,
 'letter': 588,
 'march': 589,
 'protesters': 590,
 'seen': 591,
 'water': 592,
 'lost': 593,
 'warned': 594,
 'ex': 595,
 'questions': 596,
 'nominee': 597,
 'someone': 598,
 '18': 599,
 'watch': 600,
 'district': 601,
 'such': 602,
 'union': 603,
 'business': 604,
 'officer': 605,
 'near': 606,
 '“this': 607,
 'less': 608,
 'speech': 609,
 '15': 610,
 'anyone': 611,
 'obama': 612,
 'reports': 613,
 'international': 614,
 'calls': 615,
 'looks': 616,
 'ahead': 617,
 'friends': 618,
 'kim': 619,
 'let': 620,
 'legislation': 621,
 'claim': 622,
 '12': 623,
 'jan': 624,
 'hollywood': 625,
 'staff': 626,
 'doing': 627,
 'arrested': 628,
 'lawsuit': 629,
 '30': 630,
 'instead': 631,
 'civil': 632,
 'christmas': 633,
 'center': 634,
 'alleged': 635,
 'counsel': 636,
 'thursday': 637,
 'lady': 638,
 'doesn’t': 639,
 'book': 640,
 'program': 641,
 'r': 642,
 'data': 643,
 'appeared': 644,
 'lead': 645,
 'tweet': 646,
 'evidence': 647,
 'half': 648,
 'together': 649,
 'finally': 650,
 'teachers': 651,
 'share': 652,
 'list': 653,
 'wall': 654,
 'felt': 655,
 '17': 656,
 'read': 657,
 'activist': 658,
 'different': 659,
 'everything': 660,
 'turned': 661,
 'pop': 662,
 'schools': 663,
 'trial': 664,
 'happy': 665,
 'possible': 666,
 'needs': 667,
 'hold': 668,
 'huffpost': 669,
 'issue': 670,
 'clear': 671,
 'shared': 672,
 'incident': 673,
 'mark': 674,
 'female': 675,
 'point': 676,
 'network': 677,
 "isn't": 678,
 'virus': 679,
 'serious': 680,
 'wrong': 681,
 'spoke': 682,
 'conspiracy': 683,
 'human': 684,
 'politics': 685,
 'efforts': 686,
 'that’s': 687,
 'hope': 688,
 'county': 689,
 'charged': 690,
 'congressional': 691,
 'leave': 692,
 'recently': 693,
 'soon': 694,
 'advocates': 695,
 'makes': 696,
 'member': 697,
 'each': 698,
 'problem': 699,
 'showed': 700,
 'officers': 701,
 'matter': 702,
 '4': 703,
 'executive': 704,
 'mexico': 705,
 'father': 706,
 'bring': 707,
 'stars': 708,
 'activists': 709,
 'important': 710,
 'statement': 711,
 'anything': 712,
 'effort': 713,
 'progressive': 714,
 'mother': 715,
 'ceremony': 716,
 'play': 717,
 'west': 718,
 'voting': 719,
 'university': 720,
 'toward': 721,
 'criminal': 722,
 'stand': 723,
 'sure': 724,
 'you’re': 725,
 'mike': 726,
 'intelligence': 727,
 "we're": 728,
 'process': 729,
 'third': 730,
 'protests': 731,
 'biggest': 732,
 'forces': 733,
 'weekend': 734,
 'related': 735,
 'adviser': 736,
 'due': 737,
 'continue': 738,
 'try': 739,
 '100': 740,
 'netflix': 741,
 'personal': 742,
 'system': 743,
 'foreign': 744,
 'board': 745,
 'olympic': 746,
 'racist': 747,
 'multiple': 748,
 'age': 749,
 'mental': 750,
 'term': 751,
 'nation': 752,
 'spread': 753,
 'apparently': 754,
 'murder': 755,
 'tonight': 756,
 'probe': 757,
 'couple': 758,
 'games': 759,
 "i'm": 760,
 'victory': 761,
 'can’t': 762,
 'nuclear': 763,
 'gets': 764,
 'organization': 765,
 'inside': 766,
 'girls': 767,
 'alabama': 768,
 'winning': 769,
 'online': 770,
 'we’re': 771,
 'british': 772,
 'countries': 773,
 'small': 774,
 'line': 775,
 'safety': 776,
 'became': 777,
 'speaker': 778,
 'tweets': 779,
 'done': 780,
 '―': 781,
 'winter': 782,
 'impeachment': 783,
 'viral': 784,
 'virginia': 785,
 'families': 786,
 'based': 787,
 'award': 788,
 'truth': 789,
 'ban': 790,
 'protect': 791,
 '50': 792,
 'faces': 793,
 'suspect': 794,
 'husband': 795,
 'jr': 796,
 'male': 797,
 'global': 798,
 'sent': 799,
 'critics': 800,
 'park': 801,
 'helped': 802,
 'scott': 803,
 'ways': 804,
 'culture': 805,
 'outside': 806,
 'elections': 807,
 'paid': 808,
 'break': 809,
 'brought': 810,
 'student': 811,
 'voted': 812,
 'talking': 813,
 'hopes': 814,
 'often': 815,
 'immigrants': 816,
 'korea': 817,
 "wasn't": 818,
 'reality': 819,
 'artist': 820,
 'release': 821,
 'spent': 822,
 'employees': 823,
 'tried': 824,
 'probably': 825,
 'democracy': 826,
 'kind': 827,
 'seven': 828,
 'anchor': 829,
 'heart': 830,
 'threat': 831,
 'dozens': 832,
 'posted': 833,
 'companies': 834,
 'giving': 835,
 'billion': 836,
 'jimmy': 837,
 'self': 838,
 'comedy': 839,
 'jones': 840,
 'light': 841,
 'san': 842,
 'he’s': 843,
 'gender': 844,
 'criticism': 845,
 'gay': 846,
 '25': 847,
 'goes': 848,
 'pro': 849,
 'controversial': 850,
 'education': 851,
 'c': 852,
 'popular': 853,
 'single': 854,
 'close': 855,
 "state's": 856,
 'muslim': 857,
 'confirmed': 858,
 'potential': 859,
 'ceo': 860,
 'residents': 861,
 'described': 862,
 'beyond': 863,
 'along': 864,
 'talks': 865,
 'access': 866,
 'girl': 867,
 'dr': 868,
 'continues': 869,
 'duchess': 870,
 'favorite': 871,
 'denied': 872,
 'congressman': 873,
 'hearing': 874,
 'asian': 875,
 'forced': 876,
 'brown': 877,
 'mueller': 878,
 '7': 879,
 'key': 880,
 'awards': 881,
 '11': 882,
 'performance': 883,
 'began': 884,
 'short': 885,
 'november': 886,
 "country's": 887,
 'fake': 888,
 'k': 889,
 'song': 890,
 'andrew': 891,
 'met': 892,
 'olympics': 893,
 'crime': 894,
 'cut': 895,
 'holiday': 896,
 'fall': 897,
 'missing': 898,
 'visit': 899,
 'investigating': 900,
 'stage': 901,
 'church': 902,
 'final': 903,
 'revealed': 904,
 'living': 905,
 'street': 906,
 'chris': 907,
 'meet': 908,
 'queer': 909,
 'ryan': 910,
 "'": 911,
 'mean': 912,
 'emergency': 913,
 'industry': 914,
 '“it': 915,
 'hospital': 916,
 'cause': 917,
 'address': 918,
 'whole': 919,
 'reason': 920,
 'saw': 921,
 'building': 922,
 'body': 923,
 'nations': 924,
 'started': 925,
 'faced': 926,
 'supporters': 927,
 'heard': 928,
 'deaths': 929,
 'means': 930,
 'facing': 931,
 'hair': 932,
 'rally': 933,
 'clinton': 934,
 'speak': 935,
 'korean': 936,
 'george': 937,
 'hate': 938,
 '“it’s': 939,
 'true': 940,
 'idea': 941,
 'seems': 942,
 'pretty': 943,
 'trip': 944,
 'victim': 945,
 'oscar': 946,
 'career': 947,
 'super': 948,
 'morning': 949,
 'giant': 950,
 'georgia': 951,
 'powerful': 952,
 'duke': 953,
 'color': 954,
 'doctor': 955,
 'vaccine': 956,
 'voter': 957,
 'appears': 958,
 'rules': 959,
 'advice': 960,
 'risk': 961,
 'passed': 962,
 'involved': 963,
 'injured': 964,
 'appear': 965,
 'protest': 966,
 'sexually': 967,
 'users': 968,
 'fighting': 969,
 'economic': 970,
 'yes': 971,
 'longer': 972,
 'los': 973,
 'growing': 974,
 'veteran': 975,
 'failed': 976,
 'safe': 977,
 'responded': 978,
 'strong': 979,
 'urged': 980,
 '2015': 981,
 'racism': 982,
 "year's": 983,
 'offered': 984,
 'rule': 985,
 'playing': 986,
 'emotional': 987,
 'millions': 988,
 'forward': 989,
 'ad': 990,
 'test': 991,
 'policies': 992,
 'storm': 993,
 'worked': 994,
 'attention': 995,
 'grand': 996,
 'majority': 997,
 'private': 998,
 'rock': 999,
 'iran': 1000,
 ...}

In [ ]:
type(tokenizer.word_index)

dict

In [ ]:
tokenizer.word_index['<OOV>']

1

In [ ]:
tokenizer.word_index['the']

2

In [ ]:
len(tokenizer.word_index)

26343

#### Convert Data to Sequence

In [ ]:
sequences = tokenizer.texts_to_sequences(data)

In [ ]:
sequences[0]

[163,
 352,
 11,
 16,
 9,
 162,
 544,
 3,
 5026,
 347,
 1514,
 68,
 2396,
 50,
 14,
 2,
 13517,
 198,
 4125,
 5,
 2,
 33,
 13518,
 2,
 52,
 54,
 1298,
 8,
 2,
 897]

### Convert sequence to supervised modelling problem

In [ ]:
input_sequence = []
for seq in sequences:
    if len(seq)<2:
        continue
    for i in range(1,len(seq)):
        ngram = seq[:i+1]
        input_sequence.append(ngram)

In [ ]:
max_len = max([len(i) for i in input_sequence])

In [ ]:
max_len

44

### Padding to craeet equal length sequences

In [ ]:
input = pad_sequences(input_sequence,padding='pre',maxlen=max_len)

In [ ]:
input[:3]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0, 163, 352],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0, 163, 352,  11],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 163, 352,  11,  16]], dtype=int32)

In [ ]:
x=input[:,:-1]
y=input[:,-1]

In [ ]:
x.shape

(300014, 43)

In [ ]:
y.shape

(300014,)

### Modelling Next Word Prediction Model

In [ ]:
vocab_size = len(tokenizer.word_index)+1

In [ ]:
vocab_size

26344

In [ ]:
y = np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.shape

(240011, 43)

In [ ]:
max_len = x.shape[1] ### save number of timestamps on each sequence

In [ ]:
x.shape[1]

43

#### Model Creation

In [ ]:
model = Sequential([
    Embedding(input_dim=vocab_size,output_dim=128,input_shape=(max_len,)),
    LSTM(256),
    Dense(vocab_size,activation='softmax')
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 43, 128)        │     3,372,032 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 26344)          │     6,770,408 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,536,680 (40.19 MB)

 Trainable params: 10,536,680 (40.19 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model2 = Sequential([
    Input(shape=(max_len,)),
    Embedding(input_dim=vocab_size,output_dim=128),
    LSTM(256),
    Dense(vocab_size,activation='softmax')
])

In [ ]:
model2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 43, 128)        │     3,372,032 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 26344)          │     6,770,408 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,536,680 (40.19 MB)

 Trainable params: 10,536,680 (40.19 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
# This step is needed if Input layer is not used or input_shape npt passed into the sequential model
model.build(input_shape=(None,max_len))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 43, 128)        │     3,372,032 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 26344)          │     6,770,408 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,536,680 (40.19 MB)

 Trainable params: 10,536,680 (40.19 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x_train,y_train,epochs=30,validation_data=(x_test,y_test),batch_size = 64)

Epoch 1/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 73s 19ms/step - accuracy: 0.3918 - loss: 3.1635 - val_accuracy: 0.1242 - val_loss: 8.0115
Epoch 2/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.4452 - loss: 2.8353 - val_accuracy: 0.1211 - val_loss: 8.2338
Epoch 3/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.4859 - loss: 2.5882 - val_accuracy: 0.1200 - val_loss: 8.4715
Epoch 4/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.5248 - loss: 2.3663 - val_accuracy: 0.1173 - val_loss: 8.7139
Epoch 5/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.5595 - loss: 2.1703 - val_accuracy: 0.1154 - val_loss: 8.9280
Epoch 6/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.5901 - loss: 1.9990 - val_accuracy: 0.1126 - val_loss: 9.1448
Epoch 7/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.6191 - loss: 1.8465 - val_accuracy: 0.1108 - val_loss: 9.3546
Epoch 8/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 81s 19ms/step - accuracy: 0.6454 - loss: 1.7091 - val_accuracy: 0.1080 - val_loss: 9.5814
Epoch 9/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.6687 - loss: 1.5906 - val_accuracy: 0.1076 - val_loss: 9.7826
Epoch 10/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.6898 - loss: 1.4821 - val_accuracy: 0.1063 - val_loss: 9.9977
Epoch 11/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.7078 - loss: 1.3881 - val_accuracy: 0.1033 - val_loss: 10.2147
Epoch 12/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.7259 - loss: 1.2993 - val_accuracy: 0.1020 - val_loss: 10.4068
Epoch 13/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.7418 - loss: 1.2249 - val_accuracy: 0.1000 - val_loss: 10.6125
Epoch 14/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.7556 - loss: 1.1560 - val_accuracy: 0.1003 - val_loss: 10.7946
Epoch 15/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.7681 - loss: 1.0969 - val_accuracy: 0.0995 - val_loss: 10.9715
Epoch 16/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.7787 - loss: 1.0426 - val_accuracy: 0.0981 - val_loss: 11.1567
Epoch 17/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.7878 - loss: 0.9943 - val_accuracy: 0.0992 - val_loss: 11.3010
Epoch 18/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 82s 19ms/step - accuracy: 0.7973 - loss: 0.9507 - val_accuracy: 0.0989 - val_loss: 11.4971
Epoch 19/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 73s 20ms/step - accuracy: 0.8056 - loss: 0.9120 - val_accuracy: 0.0976 - val_loss: 11.6729
Epoch 20/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.8122 - loss: 0.8783 - val_accuracy: 0.0968 - val_loss: 11.8062
Epoch 21/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.8185 - loss: 0.8475 - val_accuracy: 0.0958 - val_loss: 11.9563
Epoch 22/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.8249 - loss: 0.8170 - val_accuracy: 0.0951 - val_loss: 12.1093
Epoch 23/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.8291 - loss: 0.7963 - val_accuracy: 0.0947 - val_loss: 12.2568
Epoch 24/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.8329 - loss: 0.7744 - val_accuracy: 0.0948 - val_loss: 12.3913
Epoch 25/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 82s 19ms/step - accuracy: 0.8368 - loss: 0.7545 - val_accuracy: 0.0945 - val_loss: 12.5193
Epoch 26/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 83s 19ms/step - accuracy: 0.8412 - loss: 0.7335 - val_accuracy: 0.0940 - val_loss: 12.6593
Epoch 27/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.8439 - loss: 0.7186 - val_accuracy: 0.0941 - val_loss: 12.7634
Epoch 28/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.8480 - loss: 0.7029 - val_accuracy: 0.0945 - val_loss: 12.9037
Epoch 29/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 71s 19ms/step - accuracy: 0.8489 - loss: 0.6934 - val_accuracy: 0.0932 - val_loss: 13.0062
Epoch 30/30
3751/3751 ━━━━━━━━━━━━━━━━━━━━ 72s 19ms/step - accuracy: 0.8531 - loss: 0.6763 - val_accuracy: 0.0932 - val_loss: 13.1320

In [ ]:
model.save('nextword_model_colab1.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
import pickle
with open('tokenizer_colab1.pkl','wb') as file:
    pickle.dump(tokenizer,file)